Dies ist meine erster Versuch.

# 1. Schritt: Daten einlesen

In [1]:
import pandas as pd
%matplotlib inline

felderliste = ['Player', 'PTS', 'FG%', 'TOV%']

so kann man Felder kombinieren, die einen interessieren

In [2]:
lva_2017_berufe = "LVA_2017_Berufe.csv"

In [3]:
df = pd.read_csv(lva_2017_berufe)

In [4]:
df

,Unnamed: 0,Beruf,Total Lernende,Anzahl Lernende mit LVA,LVA-Quote
0,NaN,alle,57654.0,11901,20.6
1,211,Audiovisuelle Techniken und Medienproduktion,816.0,218,26.7
2,NaN,Flexodrucker/in EFZ,11.0,*,*
3,NaN,Printmedienpraktiker/in EBA,18.0,*,*
4,NaN,Printmedienverarbeiter/in EFZ,46.0,8,17.4
5,NaN,Drucktechnologe/-technologin EFZ,125.0,36,28.8
6,NaN,Fotofachmann/-frau EFZ,80.0,21,26.3
7,NaN,Polygraf/in EFZ,166.0,42,25.3
8,NaN,Interactive Media Designer EFZ,2.0,*,*
9,NaN,Mediamatiker/in EFZ,255.0,75,29.4
10,NaN,Veranstaltungsfachmann/-frau EFZ,19.0,*,*
11,NaN,Fotograf/in EFZ,10.0,*,*
12,NaN,Grafiker/in EFZ,84.0,22,26.2
13,212,"Mode, Innenarchitektur und industrielles Design",297.0,56,18.9
14,NaN,Dekorationsn√§her/in EBA,1.0,*,*
15,NaN,Innendekorateur/in,57.0,12,21.1
16,NaN,Wohntextilgestalter/in EFZ,15.0,*,*
17,NaN,Theatermaler/in EFZ,2.0,*,*
18,NaN,Gestalter/in Werbetechnik EFZ,136.0,30,22.1
19,NaN,Polydesigner/in 3D EFZ,86.0,11,12.8
20,214,Kunsthandwerk,312.0,69,22.1
21,NaN,Florist/in EFZ,240.0,49,20.4
22,NaN,Florist/in EBA,18.0,*,*
23,NaN,Gewebegestalter/in EFZ,1.0,*,*
24,NaN,Holzhandwerker/in EFZ,4.0,*,*
25,NaN,Vergolder/in-Einrahmer/in EFZ,3.0,*,*
26,NaN,Keramiker/in EFZ,3.0,*,*
27,NaN,Steinbildhauer/in EFZ,5.0,*,*
28,NaN,Goldschmied/in EFZ,29.0,*,*
29,NaN,Musikinstrumentenbauer/in EFZ,8.0,*,*
...,...,...,...,...,...
220,NaN,Assistent/in Gesundheit und Soziales EBA,623.0,110,17.7
221,1011,Hauswirtschaftliche Dienste,1295.0,303,23.4
222,NaN,Fachmann/-frau Hauswirtschaft EFZ,321.0,69,21.5
223,NaN,Hauswirtschaftspraktiker/in EBA,202.0,43,21.3
224,NaN,Geb√§udereiniger/in EBA,39.0,7,17.9
225,NaN,Geb√§udereiniger/in EFZ,62.0,16,25.8
226,NaN,Kaminfeger/in EFZ,61.0,12,19.7
227,NaN,Textilpfleger/in EFZ,18.0,*,*
228,NaN,Fachmann/-frau Betriebsunterhalt EFZ,592.0,147,24.8
229,1012,Friseurgewerbe und Sch√∂nheitspflege,1197.0,425,35.5
230,NaN,Coiffeur/-euse EFZ,1008.0,363,36
231,NaN,Coiffeur/-euse EBA,90.0,36,40
232,NaN,Kosmetiker/in EFZ,99.0,26,26.3
233,1013,Gastgewerbe und Catering,2810.0,903,32.1
234,NaN,Di√§tkoch/-k√∂chin EFZ,78.0,4,5.1
235,NaN,Hotellerieangestellte/r EBA,27.0,*,*
236,NaN,Hotelfachmann/-frau EFZ,297.0,65,21.9
237,NaN,Restaurationsfachmann/-frau EFZ,533.0,208,39
238,NaN,Restaurationsangestellte/r EBA,83.0,31,37.3
239,NaN,Koch/K√∂chin EFZ,1488.0,499,33.5
240,NaN,K√ºchenangestellte/r EBA,261.0,80,30.7
241,NaN,Systemgastronomiefachmann/-frau EFZ,43.0,13,30.2
242,1014,Sport,69.0,25,36.2
243,NaN,Fachmann/-frau Bewegungs- und Gesundheitsf√∂rde...,69.0,25,36.2
244,1041,Verkehrsdienstleistungen,198.0,43,21.7
245,NaN,Seilbahner/in EBA,5.0,*,*
246,NaN,Seilbahn-Mechatroniker/in EFZ,16.0,*,*
247,NaN,Matrose/Matrosin der Binnenschifffahrt EFZ,4.0,*,*
248,NaN,Strassentransportfachmann/-frau EFZ,173.0,40,23.1
249,* Ausbildungsfelder mit weniger als 30 Lehrver...,NaN,NaN,NaN,NaN

In [17]:
df['LVA-Quote'].max().tail(10)

TypeError: '>=' not supported between instances of 'str' and 'float'